
name: LEDE

on:
  repository_dispatch:
  workflow_dispatch:
    inputs:
      ssh:
        description: 'SSH connection to Actions'
        required: false
        default: 'false'
    
  pull_request: https://github.com/coolsnowwolf/lede
    branches: master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: 正在载入Ubuntu。。。。。
        run: |
          sudo apt-get update
          sudo apt-get -y install build-essential asciidoc binutils bzip2 gawk gettext git libncurses5-dev libz-dev patch python3 python2.7 unzip zlib1g-dev lib32gcc1 libc6-dev-i386 subversion flex uglifyjs git-core gcc-multilib p7zip p7zip-full msmtp libssl-dev texinfo libglib2.0-dev xmlto qemu-utils upx libelf-dev autoconf automake libtool autopoint device-tree-compiler g++-multilib antlr3 gperf wget curl swig rsync

      - name: 克隆源代码
        run: |
          git clone https://github.com/coolsnowwolf/lede
          cd lede
          ./scripts/feeds update -a
          ./scripts/feeds install -a
      
      - name: SSH连接至Actions云服务器
        uses: P3TERX/ssh2actions@v1.0.0
        if: (github.event.inputs.ssh == 'true' && github.event.inputs.ssh  != 'false') || contains(github.event.action, 'ssh')
        env:
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}

      
      - name: 下载编译所需要dl包
        run: |
          cd lede
          make -j8 download V=s   
          
      - name: 开始编译固件：请稍等..........(大概2小时左右)
        run: |
          cd lede
          echo -e "$(nproc) thread compile"
          make -j1 V=s
          
      - name : 上传固件
        uses: actions/upload-artifact@main
        with:
          name: LEDE
          path: openwrt/bin
        
