#=========================================================
# Copyright (c) 2021 baiyunxue
#
# This is free software, licensed under the MIT License.
# See /LICENSE for more information.
#
# https://github.com/baiyunxue/Compile-Openwrt
# Description: Build OpenWrt using GitHub Actions
#=========================================================

name: by-Openwrt

on:
  repository_dispatch:
  workflow_dispatch:
    inputs:
      ssh:
        description: 'SSH connection to Actions'
        required: true
        default: 'true'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 检查。。。系统运行环境
        uses: actions/checkout@v2

      - name: 正在载入Ubuntu。。。。。
        run: |
          sudo apt update
          sudo apt install build-essential ccache ecj fastjar file g++ gawk \
            gettext git java-propose-classpath libelf-dev libncurses5-dev \
            libncursesw5-dev libssl-dev python python2.7-dev python3 unzip wget \
            python3-distutils python3-setuptools python3-dev rsync subversion \
            swig time xsltproc zlib1g-dev 
      
      - name: 克隆源代码
        run: |
          git clone -b openwrt-19.07 https://git.openwrt.org/openwrt/openwrt.git
          cd openwrt
          ./scripts/feeds update -a
          ./scripts/feeds install -a
          #git clone https://github.com/baiyunxue/ZDY.git package/files
          svn co https://github.com/linkease/ddnsto-openwrt/trunk/ddnsto package/network/services/ddnsto
          svn co https://github.com/linkease/ddnsto-openwrt/trunk/luci-app-ddnsto package/files/luci-app-ddnsto
          svn co https://github.com/kiddin9/openwrt-packages/trunk/luci-app-xunlei package/files/luci-app-xunlei
          svn co https://github.com/kiddin9/openwrt-packages/trunk/luci-app-qbittorrent package/files/luci-app-qbittorrent
          git clone awesome-openwrt https://github.com/awesome-openwrt/luci-app-autoreboot.git package/DIY/luci-app-autoreboot
          git clone mchome https://github.com/mchome/luci-app-vlmcsd.git package/DIY/luci-app-vlmcsd
          git clone mchome https://github.com/mchome/openwrt-vlmcsd.git package/DIY/vlmcsd
          git clone monokoo https://github.com/monokoo/luci-app-transmission.git package/DIY/luci-app-transmission
          git clone pymumu https://github.com/pymumu/luci-app-smartdns.git package/DIY/luci-app-smartdns
          git clone pymumu https://github.com/pymumu/openwrt-smartdns.git package/DIY/smartdns
          git clone rufengsuixing https://github.com/rufengsuixing/luci-app-zerotier.git package/DIY/luci-app-zerotier
          svn co https://github.com/animefansxj/luci-app-vsftpd/trunk/Source/op-dir/feeds/packages/net/vsftpd package/DIY/vsftpd
          svn co https://github.com/animefansxj/luci-app-vsftpd/trunk/Source/luci-dir/applications/luci-vsftpd package/DIY/luci-app-vsftpd
          git clone Leo-Jo-My https://github.com/Leo-Jo-My/luci-theme-opentomato.git package/DIY/luci-theme-opentomato
          git clone Leo-Jo-My https://github.com/Leo-Jo-My/luci-theme-argon-dark-mod.git package/DIY/luci-theme-argon-dark-mod
      
      - name: SSH连接至Actions云服务器
        uses: P3TERX/ssh2actions@v1.0.0
        if: (github.event.inputs.ssh == 'true' && github.event.inputs.ssh  != 'false') || contains(github.event.action, 'ssh')
        env:
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
   
      - name: 开始编译固件：请稍等..........(大概2小时左右)
        run: |
          cd openwrt
          make -j1 V=s
          
      - name: 检查github空间使用情况
        if: (!cancelled())
        run: df -hT

      - name: 上传（固件+ipk）的bin文件夹 到github空间
        uses: actions/upload-artifact@main
        with:
          name: by-OpenWrt_bin${{ env.DEVICE_NAME }}${{ env.FILE_DATE }}
          path: openwrt/bin
